/**
 * Spice-cartel crisis mini-game (era 18) world: pure state + helpers, no React.
 * The cartel has scrambled the spice conduits; the player rotates pipe tiles to
 * relink the spice source (left) to the universe-city (right). A guaranteed-
 * solvable puzzle is generated by laying a long weaving path, fitting pieces to it,
 * then scrambling every rotation. Because tiles only turn clockwise, the scramble
 * is forced far enough from the solution that it takes at least `minMoves` turns.
 * The crisis runs THREE stages, each wider (more columns) and harder; SpiceGame.tsx
 * drives the stages. Connectivity is recomputed each render (the grid is small).
 * Directions are indexed N=0, E=1, S=2, W=3.
 */
export const ROWS = 3
export const SRC_ROW = 1
export const DST_ROW = 1
export const STAGES = 3
const colsForStage = (stage: number) => 6 + stage * 2 // 8, 10, 12
const minMovesForStage = (stage: number) => 11 + stage * 4 // 15, 19, 23

/** Unit vectors per direction in SCREEN coords (N points up), for drawing pipes. */
export const DIR_VEC: readonly [number, number][] = [
  [0, -1],
  [1, 0],
  [0, 1],
  [-1, 0],
]

// Grid-coord delta (row, col) per direction, for adjacency walks.
const GRID_DELTA: readonly [number, number][] = [
  [-1, 0],
  [0, 1],
  [1, 0],
  [0, -1],
]

type PipeType = 'straight' | 'elbow' | 'tee'
interface Tile {
  type: PipeType
  rot: number
}
export interface SpiceWorld {
  cols: number
  tiles: Tile[]
}

// Open sides of each piece at rotation 0; a rotation adds `rot` to every side.
const BASE: Record<PipeType, number[]> = {
  straight: [0, 2],
  elbow: [0, 1],
  tee: [0, 1, 2],
}

const idx = (r: number, c: number, cols: number) => r * cols + c

/** Open sides of a tile, accounting for its rotation. */
export function openings(tile: Tile): number[] {
  return BASE[tile.type].map((d) => (d + tile.rot) % 4)
}

const randInt = (a: number, b: number) => a + Math.floor(Math.random() * (b - a + 1))
const dirTo = (r: number, c: number, r2: number, c2: number) =>
  r2 === r - 1 ? 0 : c2 === c + 1 ? 1 : r2 === r + 1 ? 2 : 3

// A path tile's solution: a straight matches a parity (rot % 2), an elbow matches
// one exact rotation. `cost` is the clockwise turns from `rot` to that solution.
interface Solution {
  i: number
  kind: 'straight' | 'elbow'
  correct: number
}
const cost = (s: Solution, rot: number) =>
  s.kind === 'straight' ? (rot % 2 === s.correct ? 0 : 1) : (s.correct - rot + 4) % 4
const maxCost = (s: Solution) => (s.kind === 'straight' ? 1 : 3)
const setCost = (s: Solution, target: number) =>
  s.kind === 'straight' ? (target === 0 ? s.correct : 1 - s.correct) : (s.correct - target + 4) % 4

function build(cols: number, minMoves: number): { tiles: Tile[]; movesNeeded: number } {
  // Weave a left-to-right path: every interior column moves to a different row, so
  // the route is full of turns (elbows) rather than one obvious straight line.
  const order: [number, number][] = []
  let r = SRC_ROW
  order.push([r, 0])
  for (let c = 1; c < cols; c++) {
    order.push([r, c])
    const target = c === cols - 1 ? DST_ROW : (r + 1 + randInt(0, ROWS - 2)) % ROWS // any row but r
    while (r !== target) {
      r += Math.sign(target - r)
      order.push([r, c])
    }
  }

  const solutions = new Map<number, Solution>()
  for (let i = 0; i < order.length; i++) {
    const [cr, cc] = order[i]!
    const dirs: number[] = []
    if (i > 0) dirs.push(dirTo(cr, cc, order[i - 1]![0], order[i - 1]![1]))
    if (i < order.length - 1) dirs.push(dirTo(cr, cc, order[i + 1]![0], order[i + 1]![1]))
    if (i === 0) dirs.push(3)
    if (i === order.length - 1) dirs.push(1)
    const opposite = (dirs[0]! + 2) % 4 === dirs[1]!
    const correct = opposite
      ? dirs[0]! % 2 // straight: parity that yields these openings
      : (dirs[0]! + 1) % 4 === dirs[1]!
        ? dirs[0]! // elbow: rotation whose two clockwise sides match
        : dirs[1]!
    const gi = idx(cr, cc, cols)
    solutions.set(gi, { i: gi, kind: opposite ? 'straight' : 'elbow', correct })
  }

  const types: PipeType[] = ['straight', 'elbow', 'tee']
  const tiles: Tile[] = []
  for (let i = 0; i < ROWS * cols; i++) {
    const sol = solutions.get(i)
    if (!sol) {
      tiles.push({ type: types[randInt(0, 2)]!, rot: randInt(0, 3) })
      continue
    }
    // Scramble every path tile at least one turn away from its solution.
    let rot = randInt(0, 3)
    if (cost(sol, rot) === 0) rot = (rot + 1) % 4
    tiles.push({ type: sol.kind, rot })
  }

  const sols = [...solutions.values()]
  let moves = sols.reduce((sum, s) => sum + cost(s, tiles[s.i]!.rot), 0)
  // Bump tiles a turn further (round-robin) until the solution needs >= minMoves.
  for (let pass = 0; moves < minMoves; pass++) {
    let bumped = false
    for (const s of sols) {
      if (moves >= minMoves) break
      const tile = tiles[s.i]!
      const cur = cost(s, tile.rot)
      if (cur < maxCost(s)) {
        tile.rot = setCost(s, cur + 1)
        moves++
        bumped = true
      }
    }
    if (!bumped) break
  }
  return { tiles, movesNeeded: moves }
}

export function freshSpice(stage: number): SpiceWorld {
  const cols = colsForStage(stage)
  const minMoves = minMovesForStage(stage)
  // Retry until the layout can actually demand minMoves (a short weave can't).
  let best = build(cols, minMoves)
  for (let tries = 0; tries < 8 && best.movesNeeded < minMoves; tries++)
    best = build(cols, minMoves)
  return { cols, tiles: best.tiles }
}

/** Rotates one tile a quarter-turn (the player's only move). */
export function rotate(world: SpiceWorld, i: number): SpiceWorld {
  return {
    ...world,
    tiles: world.tiles.map((t, k) => (k === i ? { ...t, rot: (t.rot + 1) % 4 } : t)),
  }
}

export interface SpiceFlow {
  flowing: boolean[]
  solved: boolean
  reach: number
}

/** Flood the spice from the inlet through connected openings; report which tiles
 *  carry spice, how far east it reaches, and whether it reaches the city outlet. */
export function computeFlow(world: SpiceWorld): SpiceFlow {
  const { tiles, cols } = world
  const flowing = new Array<boolean>(ROWS * cols).fill(false)
  const start = idx(SRC_ROW, 0, cols)
  if (openings(tiles[start]!).includes(3)) {
    const queue = [start]
    flowing[start] = true
    while (queue.length) {
      const cur = queue.shift()!
      const cr = Math.floor(cur / cols)
      const cc = cur % cols
      for (const d of openings(tiles[cur]!)) {
        const [dr, dc] = GRID_DELTA[d]!
        const nr = cr + dr
        const nc = cc + dc
        if (nr < 0 || nr >= ROWS || nc < 0 || nc >= cols) continue
        const n = idx(nr, nc, cols)
        if (!flowing[n] && openings(tiles[n]!).includes((d + 2) % 4)) {
          flowing[n] = true
          queue.push(n)
        }
      }
    }
  }
  const out = idx(DST_ROW, cols - 1, cols)
  const solved = flowing[out]! && openings(tiles[out]!).includes(1)
  let reach = 0
  for (let i = 0; i < flowing.length; i++) if (flowing[i]) reach = Math.max(reach, i % cols)
  return { flowing, solved, reach }
}
