import {
  ArrowDownRight,
  Atom,
  Axe,
  Backpack,
  Bomb,
  Brain,
  Building2,
  Calendar,
  Circle,
  CircleDot,
  Cloud,
  Cog,
  Coins,
  Copy,
  Cpu,
  Crown,
  Dna,
  Download,
  Droplet,
  Fish,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Hammer,
  Hexagon,
  Landmark,
  Leaf,
  Lightbulb,
  Orbit,
  PawPrint,
  PartyPopper,
  Pause,
  Play,
  Radar,
  Rocket,
  RotateCcw,
  Satellite,
  Settings,
  Skull,
  Sparkles,
  Star,
  Sunrise,
  Swords,
  Telescope,
  Trees,
  Trophy,
  Upload,
  X,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { ReactElement, SVGProps } from 'react'
import {
  AtmosphereIcon,
  CardIcon,
  CellIcon,
  ComplexCellIcon,
  BurstIcon,
  DistrictIcon,
  DnaStrandIcon,
  DustIcon,
  FloraIcon,
  FusionIcon,
  JerrycanIcon,
  ShipIcon,
  SolarSystemIcon,
  StarClusterIcon,
  UniverseCityIcon,
  EchoIcon,
  ElectronIcon,
  EllipseIcon,
  EukaryoteIcon,
  MoleculeIcon,
  NucleonIcon,
  OrganelleIcon,
  TissueIcon,
  TrilobiteIcon,
  VirusIcon,
} from '@/components/art/glyphs'

type Glyph = LucideIcon | ((props: SVGProps<SVGSVGElement>) => ReactElement)

/**
 * Icon registry: data only references an identifier (string); the mapping to
 * the icon library (lucide) or a custom glyph (./glyphs) lives here (UI). Adding
 * a resource = adding its entry here if its icon does not exist yet.
 */
const ICONS: Record<string, Glyph> = {
  sparkles: Sparkles,
  circle: Circle,
  'circle-dot': CircleDot,
  zap: Zap,
  atom: Atom,
  axe: Axe,
  cog: Cog,
  calendar: Calendar,
  party: PartyPopper,
  gem: Gem,
  flame: Flame,
  orbit: Orbit,
  cloud: Cloud,
  atmosphere: AtmosphereIcon,
  card: CardIcon,
  star: Star,
  sunrise: Sunrise,
  'star-cluster': StarClusterIcon,
  'solar-system': SolarSystemIcon,
  fusion: FusionIcon,
  'dna-strand': DnaStrandIcon,
  lightbulb: Lightbulb,
  telescope: Telescope,
  radar: Radar,
  burst: BurstIcon,
  ellipse: EllipseIcon,
  electron: ElectronIcon,
  nucleon: NucleonIcon,
  cell: CellIcon,
  'complex-cell': ComplexCellIcon,
  organelle: OrganelleIcon,
  eukaryote: EukaryoteIcon,
  trilobite: TrilobiteIcon,
  tissue: TissueIcon,
  flora: FloraIcon,
  dust: DustIcon,
  molecule: MoleculeIcon,
  virus: VirusIcon,
  hexagon: Hexagon,
  globe: Globe,
  flask: FlaskConical,
  dna: Dna,
  droplet: Droplet,
  leaf: Leaf,
  fish: Fish,
  paw: PawPrint,
  trees: Trees,
  brain: Brain,
  hammer: Hammer,
  users: Users,
  city: Building2,
  landmark: Landmark,
  coins: Coins,
  crown: Crown,
  trophy: Trophy,
  swords: Swords,
  cpu: Cpu,
  rocket: Rocket,
  ship: ShipIcon,
  jerrycan: JerrycanIcon,
  satellite: Satellite,
  district: DistrictIcon,
  'universe-city': UniverseCityIcon,
  echo: EchoIcon,
  bomb: Bomb,
  skull: Skull,
  backpack: Backpack,
  close: X,
  pause: Pause,
  play: Play,
  settings: Settings,
  download: Download,
  upload: Upload,
  'rotate-ccw': RotateCcw,
  'arrow-down-right': ArrowDownRight,
  copy: Copy,
}

export function Icon({ name, className }: { name: string; className?: string }) {
  const Glyph = ICONS[name] ?? CircleDot
  return <Glyph className={className} aria-hidden />
}
