import {
  Atom,
  Bomb,
  Brain,
  Building2,
  CircleDot,
  Cloud,
  Cog,
  Coins,
  Copy,
  Cpu,
  Crown,
  Disc,
  Dna,
  Download,
  Droplet,
  Fish,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Hammer,
  Hexagon,
  Landmark,
  Leaf,
  Network,
  Orbit,
  PawPrint,
  Pause,
  Play,
  Rocket,
  RotateCcw,
  Satellite,
  Settings,
  Skull,
  Sparkles,
  Star,
  Swords,
  Trees,
  Upload,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icon registry: data only references an identifier (string); the mapping to
 * the icon library lives here (UI). Adding a resource = adding its entry here
 * if its icon does not exist yet.
 */
const ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  'circle-dot': CircleDot,
  zap: Zap,
  atom: Atom,
  cog: Cog,
  gem: Gem,
  flame: Flame,
  orbit: Orbit,
  cloud: Cloud,
  star: Star,
  disc: Disc,
  hexagon: Hexagon,
  globe: Globe,
  flask: FlaskConical,
  dna: Dna,
  droplet: Droplet,
  leaf: Leaf,
  fish: Fish,
  paw: PawPrint,
  trees: Trees,
  brain: Brain,
  hammer: Hammer,
  users: Users,
  city: Building2,
  landmark: Landmark,
  coins: Coins,
  crown: Crown,
  swords: Swords,
  cpu: Cpu,
  rocket: Rocket,
  satellite: Satellite,
  network: Network,
  bomb: Bomb,
  skull: Skull,
  pause: Pause,
  play: Play,
  settings: Settings,
  download: Download,
  upload: Upload,
  'rotate-ccw': RotateCcw,
  copy: Copy,
}

export function Icon({ name, className }: { name: string; className?: string }) {
  const Glyph = ICONS[name] ?? CircleDot
  return <Glyph className={className} aria-hidden />
}
